services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage
      POSTGRES_DB: storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storage"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: distributed-storage
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://storage:storage@postgres:5432/storage?sslmode=disable"
      MAX_UPLOAD_SIZE_MB: "100"
      STORAGE_NODE_URLS: "http://storage_node_1:8081,http://storage_node_2:8081,http://storage_node_3:8081"
      STORAGE_NODE_TOKEN: "${STORAGE_NODE_TOKEN}"
      
    depends_on:
      postgres:
        condition: service_healthy

  storage_node_1:
    build: .
    container_name: storage-node-1
    command: /app/storage-node
    ports:
      - "8081:8081"
    volumes:
      - file_storage_1:/app/storage
    environment:
      STORAGE_NODE_TOKEN: "${STORAGE_NODE_TOKEN}"
  
  storage_node_2:
    build: .
    container_name: storage-node-2
    command: /app/storage-node
    ports:
      - "8082:8081"
    volumes:
      - file_storage_2:/app/storage
    environment:
      STORAGE_NODE_TOKEN: "${STORAGE_NODE_TOKEN}"

  storage_node_3:
    build: .
    container_name: storage-node-3
    command: /app/storage-node
    ports:
      - "8083:8081"
    volumes:
      - file_storage_3:/app/storage

    environment:
      STORAGE_NODE_TOKEN: "${STORAGE_NODE_TOKEN}"

volumes:
  postgres_data:
  file_storage_1:
  file_storage_2:
  file_storage_3: